export const artList = [
    'ASOCIART S.A. ASEGURADORA DE RIESGOS DEL TRABAJO',
    'Berkley International A.R.T. S.A.',
    'Caja Popular de Ahorros de la Provincia de Tucumán',
    'Caminos Protegidos Aseguradora de Riesgos del Trabajo S.A.',
    'EXPERIENCIA ART S.A.',
    'Experta Aseguradora de Riesgos del Trabajo S.A.',
    'Federación Patronal Seguros S.A.',
    'GALENO ART S.A.',
    'Horizonte Compañía Argentina de Seguros Grales. S.A.',
    'Instituto Autárquico Provincial del Seguro de Entre Ríos',
    'Aseguradora de Riesgos de Trabajo Interacción S.A.',
    'La Holando Sudamericana Compañía de Seguros S.A.',
    'La Segunda Aseguradora de Riesgos del Trabajo S.A.',
    'Compañía Argentina de Seguros Latitud Sur S.A.',
    'ASEGURADORA DE RIESGOS DEL TRABAJO LIDERAR S.A.',
    'OMINT ASEGURADORA DE RIESGOS DEL TRABAJO S.A.',
    'Prevención Aseguradora de Riesgos del Trabajo S.A.',
    'Productores de Frutas Argentinas Cooperativa de Seguros Limitada',
    'Provincia Aseguradora de Riesgos del Trabajo S.A.',
    'Reconquista A.R.T. S.A.',
    'SWISS MEDICAL ART S.A.',
    'Compañía Argentina de Seguros Victoria S.A.',
];
