export const obrasSociales = [
    { codigo: '000000', descripcion: 'Ninguna' },
    { codigo: '000406', descripcion: 'OS del Personal de Organismos de Control Externo' },
    { codigo: '000802', descripcion: 'OS de Y.P.F.' },
    { codigo: '000901', descripcion: 'OS de la Actividad de Seguros, Reaseguros, Capitalización, Ahorro y Préstamo para la Vivienda' },
    { codigo: '001003', descripcion: 'OS del Personal de Obras y Servicios Sanitarios' },
    { codigo: '001102', descripcion: 'OS para la Actividad Docente' },
    { codigo: '001201', descripcion: 'OS Personal Ministerio Economía y de Obras y Servicios Públicos' },
    { codigo: '001805', descripcion: 'OS de Legisladores de la Republica Argentina' },
    { codigo: '002501', descripcion: 'OS Ministros, Secretarios y Subsecretarios' },
    { codigo: '002600', descripcion: 'OS Trabajadores de la Carne y Afines de la R.A. (OSCARA)' },
    { codigo: '002709', descripcion: 'OS de los Trabajadores Asoc. Mutual Mercantil Arg. (OSTAMMA)' },
    { codigo: '002808', descripcion: 'OS de la Cámara de Empresario de agencias de remises de Argentina (OSCEARA)' },
    { codigo: '002907', descripcion: 'OS Mutual Metalúrgica Villa Constitución (OSAMMVC)' },
    { codigo: '003009', descripcion: 'OS Personal Asociado a la Asociación Mutual Sancor (OSPERSAAMS)' },
    { codigo: '003108', descripcion: 'Obra Social de los Inmigrantes Españoles y sus descendientes Residentes en la R.A.' },
    { codigo: '003702', descripcion: 'O.S. YACIMIENTOS CARBONIFEROS FISCALES' },
    { codigo: '003801', descripcion: 'OBRA SOCIAL DE LA PREVENCION Y LA SALUD' },
    { codigo: '003900', descripcion: 'OS de Técnicos de Vuelo de Líneas Aéreas' },
    { codigo: '127208', descripcion: 'OS de Mandos Medios de Telecomunicaciones en la R.A. y MERCOSUR (OSMMEDT)' },
    { codigo: '128102', descripcion: 'OBRA SOCIAL DE LA UNION DE TRABAJADORES DEL INSSJP' },
    { codigo: '128201', descripcion: 'OS DEL SINDICATO UNICO DE RECOLECTORES DE RESIDUOS' },
    { codigo: '128508', descripcion: 'OBRA SOCIAL DE FARMACEUTICOS Y BIOQUIMICOS' },
    { codigo: '400107', descripcion: 'OS Personal de Dirección de Empresas de Alimentación' },
    { codigo: '400800', descripcion: 'Organización de Servicios Directos Empresarios' },
    { codigo: '400909', descripcion: 'OS Acción Social de Empresarios' },
    { codigo: '401506', descripcion: 'Prestadores y Dirección Empresas de Producción, Industria, Comercio y Servicios' },
    { codigo: '401605', descripcion: 'OS del Personal Dirección Industria Privada del Petróleo' },
    { codigo: '401704', descripcion: 'OS de Directivos y Empresarios Pequeños y Medianos' },
    { codigo: '401803', descripcion: 'OS Asociación Mutual del Personal de Philips Argentina (AMPAR)' },
    { codigo: '401902', descripcion: 'OS Personal de Dirección de Perfumerías E. W.Hope' },
    { codigo: '402004', descripcion: 'OS del Personal de Dirección de la Sanidad Luis Pasteur' },
    { codigo: '402509', descripcion: 'OS YPF' },
    { codigo: '901105', descripcion: 'GALENO ARGENTINA S.A.' },
    { codigo: '901402', descripcion: 'MEDIFE ASOCIACION CIVIL' },
    { codigo: '901501', descripcion: 'HOMINIS S.A.' },
    { codigo: '902108', descripcion: 'ASOCIACION MUTUAL SANCOR' },
    { codigo: '902504', descripcion: 'HOSPITAL BRITANICO DE BS. AS. ASOCIACION CIVIL' },
    { codigo: '902702', descripcion: 'SOCIEDAD ITALIANA DE BENEFICENCIA EN BS AS' },
    { codigo: '902900', descripcion: 'OMINT' },
    { codigo: '903002', descripcion: 'ASOC. CIVIL DE ESTUDIOS SUPERIORES (HOSP. AUSTRAL)' },
];
